CUSTOMERS = {
    "CUST-001": {
        "id": "CUST-001",
        "name": "John Martinez",
        "email": "john.martinez@email.com",
        "phone": "+1-555-0101",
        "plan": "Premium",
        "account_status": "Active",
        "balance_usd": 0.00,
        "member_since": "2019-03-15",
        "recent_order_ids": ["ORD-1001"],
        "notes": "Loyal customer since 2019. Prefers quick resolutions.",
    },
    "CUST-002": {
        "id": "CUST-002",
        "name": "Sarah Chen",
        "email": "sarah.chen@email.com",
        "phone": "+1-555-0102",
        "plan": "Standard",
        "account_status": "Active",
        "balance_usd": -45.00,
        "member_since": "2021-06-20",
        "recent_order_ids": ["ORD-1002"],
        "notes": "Has an open billing dispute. Handle with care.",
    },
    "CUST-003": {
        "id": "CUST-003",
        "name": "Robert Johnson",
        "email": "robert.j@corpmail.com",
        "phone": "+1-555-0103",
        "plan": "Enterprise",
        "account_status": "Active",
        "balance_usd": 0.00,
        "member_since": "2017-11-08",
        "recent_order_ids": ["ORD-1003"],
        "notes": "Corporate account. High-value client. Purchasing director.",
    },
    "CUST-004": {
        "id": "CUST-004",
        "name": "Emily Rodriguez",
        "email": "emily.r@email.com",
        "phone": "+1-555-0104",
        "plan": "Basic",
        "account_status": "Overdue",
        "balance_usd": -120.50,
        "member_since": "2022-09-14",
        "recent_order_ids": ["ORD-1004"],
        "notes": "Payment overdue 45 days. Account restrictions may apply.",
    },
    "CUST-005": {
        "id": "CUST-005",
        "name": "Michael Thompson",
        "email": "m.thompson@email.com",
        "phone": "+1-555-0105",
        "plan": "Premium",
        "account_status": "Active",
        "balance_usd": 0.00,
        "member_since": "2020-01-22",
        "recent_order_ids": ["ORD-1005"],
        "notes": "Filed 2 previous delivery complaints. Monitor satisfaction.",
    },
    "CUST-006": {
        "id": "CUST-006",
        "name": "Lisa Anderson",
        "email": "lisa.anderson@email.com",
        "phone": "+1-555-0106",
        "plan": "Standard",
        "account_status": "Pending Cancellation",
        "balance_usd": 0.00,
        "member_since": "2020-07-30",
        "recent_order_ids": ["ORD-1006"],
        "notes": "Cancellation request submitted. Retention offer pending.",
    },
    "CUST-007": {
        "id": "CUST-007",
        "name": "David Kim",
        "email": "d.kim@techcorp.com",
        "phone": "+1-555-0107",
        "plan": "Enterprise",
        "account_status": "Active",
        "balance_usd": 500.00,
        "member_since": "2016-04-10",
        "recent_order_ids": ["ORD-1007"],
        "notes": "VIP client. CTO of TechCorp. Escalate complex issues immediately.",
    },
    "CUST-008": {
        "id": "CUST-008",
        "name": "Jennifer Williams",
        "email": "jen.williams@email.com",
        "phone": "+1-555-0108",
        "plan": "Basic",
        "account_status": "Active",
        "balance_usd": 0.00,
        "member_since": "2024-02-03",
        "recent_order_ids": ["ORD-1008"],
        "notes": "New customer. First support contact.",
    },
    "CUST-009": {
        "id": "CUST-009",
        "name": "Christopher Davis",
        "email": "chris.davis@email.com",
        "phone": "+1-555-0109",
        "plan": "Premium",
        "account_status": "Active",
        "balance_usd": 25.00,
        "member_since": "2018-08-17",
        "recent_order_ids": ["ORD-1009", "ORD-1001"],
        "notes": "Frequent buyer. Enrolled in TechMart Rewards. Platinum tier.",
    },
    "CUST-010": {
        "id": "CUST-010",
        "name": "Amanda Wilson",
        "email": "a.wilson@email.com",
        "phone": "+1-555-0110",
        "plan": "Standard",
        "account_status": "Locked",
        "balance_usd": 0.00,
        "member_since": "2021-12-05",
        "recent_order_ids": ["ORD-1010"],
        "notes": "Account locked due to suspicious login activity. Requires identity verification.",
    },
}


def get_customer(customer_id: str) -> dict | None:
    return CUSTOMERS.get(customer_id)


def list_customers() -> list[dict]:
    return [
        {
            "id": c["id"],
            "name": c["name"],
            "plan": c["plan"],
            "account_status": c["account_status"],
        }
        for c in CUSTOMERS.values()
    ]
